// knhk-sidecar: Generated proto code
// This module will be populated by tonic-build from kgc.proto

// Note: Proto code is generated at build time by build.rs
// The actual types will be available after `cargo build`

pub mod kgc {
    // These types will be generated by tonic-build
    // For now, we'll use placeholder types that match the proto structure
    
    pub mod kgc_service_client {
        // Placeholder - will be replaced by generated code
    }
    
    pub mod kgc_service_server {
        // Placeholder - will be replaced by generated code
    }
}

